import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../../generated-schema/product.api"; // generated by openapi-typescript
import ProductRow from './product-row';
import { useAuth0 } from "@auth0/auth0-react";
import { useEffect, useState } from "react";


const ProductListPage = () => {
  //  const { getAccessTokenSilently } = useAuth0();
  // const [products, setProducts] = useState(null);

  // useEffect(() => {
  //   (async () => {
  //     try {
  //       const token = await getAccessTokenSilently({
  //         authorizationParams: {
  //           audience: 'http://localhost:5000', // Value in Identifier field for the API being called.
  //           scope: 'read:products', // Scope that exists for the API being called. You can create these through the Auth0 Management API or through the Auth0 Dashboard in the Permissions view of your API.
  //         }
  //       });
  //       // const response = await fetch('http://localhost:5000/products', {
  //       //   headers: {
  //       //     Authorization: `Bearer ${token}`,
  //       //   },
  //       // });
  //       // setProducts(await response.json());
  //     } catch (e) {
  //       console.error(e);
  //     }
  //   })();
  // }, [getAccessTokenSilently]);

  const fetchClient = createFetchClient<paths>({
    baseUrl: "http://localhost:5000/",
    fetch: (input, init = {}) => {
      // Add Authorization header if accessToken is available
      const headers = new Headers(init.headers || {});
      // if (accessToken) {
      //   headers.set("Authorization", `Bearer ${accessToken}`);
      // }
      return fetch(input, { ...init, headers });
    },
  });
  const $api = createClient(fetchClient);

  const { data, error, isLoading: isQueryLoading } = $api.useQuery(
    "get",
    "/Product/products",
    {
      parameters: {
        productCategoryId: { productCategoryId: 1 },
      },
     // enabled: !!accessToken, // Only run query if token is available
    }
  );

  if (isQueryLoading) return <div>Loading products...</div>;
  if (error) return <div>Error loading products: {(error as Error).message}</div>;
  if (!data) return <div>No products found.</div>;

  return (
    <section>
      <h1>Products</h1>
      {data.map(item => (
        <ProductRow key={item.productId} product={item} />
      ))}
    </section>
  );
};


export default ProductListPage;