 

import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../../generated-schema/product.api"; // generated by openapi-typescript
import ProductRow from './product-row';


const ProductListPage = () => {

  const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:5000/",
});
const $api = createClient(fetchClient);


  const { data, error, isLoading } = $api.useQuery(
    "get",
    "/Product/products",
    {
      parameters: {
        productCategoryId: { productCategoryId: 1 },
      },
    });
    if (isLoading || !data) return "Loading...";
    return (
    <section>
      <h1>Products</h1>
      {data.map(item => (
          <ProductRow key={item.productId} product={item} />
      ))}
    </section>
  );
};


export default ProductListPage