openapi: 3.0.4
info:
  title: avantech.OrderingsSystem.Api
  version: '1.0'
paths:
  /:
    get:
      tags:
        - avantech.OrderingsSystem.Api
      responses:
        '200':
          description: OK
  /Product/products:
    get:
      tags:
        - Product
      parameters:
        - name: productCategoryId
          in: query
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          maxLength: 50
          minLength: 0
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        price:
          type: number
          format: double
          nullable: true
        productCategoryId:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false